source "%val{config}/plugins/plugrc.kak"
source "%val{config}/fzf.kak"

set global ui_options ncurses_set_title=false

declare-user-mode find
map global -docstring 'find' user 'f' ':enter-user-mode find<ret>'
map global -docstring 'file' find 'f' ':fzf-edit<ret>'

declare-user-mode tmux
map global -docstring 'tiling' user 't' ':enter-user-mode tmux<ret>'
map global -docstring 'split' tmux 's' ':tmux-terminal-vertical kak -c %val{session}<ret>'
map global -docstring 'vsplit' tmux 'v' ':tmux-terminal-horizontal kak -c %val{session}<ret>'
